### ISSUE TITLE
New feature: character blacklisting

### ISSUE THREAD

**Issue by adrien-cotte** [Yunight/SmashModeOnline#2]
Hello,

Thanks to Glutonny I have discover your app.
It is awesome but I would like an option to "lock" or "blacklist" certain characters, because RESET button do no have a memory.

What do you think?

Best,

**Comment by Yunight** [comment]
Hello Adrien,

Currently you can clic on the character you want to disable and it will turn unavailable for the random selection, i'm developping the version 1.2 of the app and things will change, i'll eventually add the save feature when you create an account etc..

**Comment by adrien-cotte** [comment]
Yes, but when I click on reset button I would like to keep the manually disabled chars.
I am a lazy fellow lol :)
By the way, thank you for your very quick answer I am waiting for 1.2 release.
Carry on, your project is a great.

**Comment by Yunight** [comment]
I do understand what you want, this feature will be there one day ! ;) 

Thank you for the support !
